### PR TITLE
Issue 6

### PR DESCRIPTION
**Pull request by kaiiam**
Addressing #6

### CODE REVIEW

**Comment by kaiiam** [comment]
@ramonawalls the Robot Template is complete! It can be downloaded as csv from the google sheet, complied into owl, and i'ved used direct import in protege to import the module into the edit owl file. I'll leave it to you to merge assuming that it won't create any merge conflicts with your existing branches.

**Comment by kaiiam** [comment]
@ramonawalls hold the phone for now, when I tried to run `./run.sh make all_imports` I get the error:

```
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://www.w3.org/2002/07/owl> Cause: /Users/kai/Desktop/software/ua_src/srpdio/src/modules/SRPDIO_internal_vocab.owl (No such file or directory)
```

I think it might be because I didn't add an `ontology-iri` which might be why the direct import in the local path is named `<http://www.w3.org/2002/07/owl>`. 

I'm going to try adding `--ontology-iri "http://purl.obolibrary.org/srpdio/modules/SRPDIO_internal_vocab.owl"`, and redoing the direct import.

**Comment by kaiiam** [comment]
I've added the ontology iri and reloaded, however I still get a similar error with the location of the direct import when I try to run all imports. @ramonawalls any thoughts on what I might try next?

**Comment by kaiiam** [comment]
The issue is that when I run `./run.sh make all_imports` it throws an error. 

I have an idea what the issue might be concerning the `catalog-v001.xml` file as @ddooley had suggested. I check in with the protege wiki on [Importing_Ontologies_in_P41](https://protegewiki.stanford.edu/wiki/Importing_Ontologies_in_P41) but its a bit dated. Upon manual direct import of this new owl module in protege, It add the following line to the catalog file.

```
<uri id="Imports Wizard Entry" name="http://purl.obolibrary.org/srpdio/modules/SRPDIO_internal_vocab.owl" uri="file:/Users/kai/Desktop/software/ua_src/srpdio/src/modules/SRPDIO_internal_vocab.owl"/>

```

Where the path is an absolute path on my computer. Looking at the examples of catalog files in [OBI](https://github.com/obi-ontology/obi/blob/master/src/ontology/catalog-v001.xml) and [ENVO](https://github.com/EnvironmentOntology/envo/blob/master/src/envo/catalog-v001.xml), they both have their imported modules within subdirectories of their ontology edit directory (same with FOODON). Here in SRPDIO, I tried to follow what I though was the DOSDP convention of putting a modules directory under src. I bet that if I were to move it to a subdirectory of `src/ontology`, I wouldn't get this issue.

**Comment by kaiiam** [comment]
Yes it works! I was able to run `./run.sh make all_imports` without any issue, (changes not committed in this branch here) and I was able to use protege to directly import the robot template generated owl file into the ontology, which created a functioning catalog file containing the line:

```
    <uri id="Imports Wizard Entry" name="http://purl.obolibrary.org/srpdio/modules/SRPDIO_internal_vocab.owl" uri="modules/SRPDIO_internal_vocab.owl"/>
```

**Comment by ramonawalls** [comment]
Thanks for working this out, @kaiiam. You should be able to import to Protege regardless of where the files are located, but I think having the modules in a subdirectory makes sense.

**Comment by kaiiam** [comment]
I believe the issue was that although I was able to import modules that
were located in a path above the ontology file, I was not able to not able
to run make imports from the make file. But I agree that having mods as
subdir makes sense and fixes this issue.

**Pull request merged**
